# Generated by Django 3.0.3 on 2020-07-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=200)),
                ('user_nick', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=500)),
                ('user_last_kind', models.CharField(max_length=500)),
                ('user_loc_x', models.FloatField()),
                ('user_loc_y', models.FloatField()),
            ],
        ),
    ]
