# Generated by Django 3.0.3 on 2020-07-20 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rest_kind',
            fields=[
                ('res_kind_num', models.IntegerField(primary_key=True, serialize=False)),
                ('res_kind_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_number', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('user_pw', models.CharField(max_length=200)),
                ('user_nick', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=500)),
                ('uesr_loc_x', models.FloatField()),
                ('uesr_loc_y', models.FloatField()),
                ('user_last_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.Rest_kind')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('rest_num', models.IntegerField(primary_key=True, serialize=False)),
                ('rest_name', models.CharField(max_length=500)),
                ('rest_star', models.IntegerField()),
                ('rest_address', models.CharField(max_length=500)),
                ('rest_time', models.CharField(max_length=100)),
                ('rest_tele', models.CharField(max_length=100)),
                ('rest_review', models.IntegerField()),
                ('rest_detail_link', models.CharField(max_length=500)),
                ('rest_kind_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.Rest_kind')),
            ],
        ),
    ]
