# Generated by Django 3.0.3 on 2020-07-18 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rest_kind',
            fields=[
                ('res_kind_num', models.IntegerField(primary_key=True, serialize=False)),
                ('res_kind_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_number', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('user_pw', models.CharField(max_length=200)),
                ('user_last_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.Rest_kind')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_num', models.IntegerField(default=-2)),
                ('rest_name', models.CharField(max_length=500)),
                ('rest_star', models.IntegerField(default=-3)),
                ('rest_address', models.CharField(max_length=500)),
                ('rest_detail_link', models.CharField(max_length=500)),
                ('rest_kind_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.Rest_kind')),
            ],
        ),
    ]
