# Generated by Django 3.0.3 on 2020-07-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_last_name1',
            field=models.CharField(default='오점뭐!', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='user_last_name2',
            field=models.CharField(default='오점뭐!', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='user_last_name3',
            field=models.CharField(default='오점뭐!', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='user_last_name4',
            field=models.CharField(default='오점뭐!', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='user_last_name5',
            field=models.CharField(default='오점뭐!', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_last_kind',
            field=models.CharField(default='오점뭐!', max_length=500),
        ),
    ]
