# Generated by Django 3.0.3 on 2020-07-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uesr_loc_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='uesr_loc_y',
            field=models.FloatField(default=0),
        ),
    ]
