# Generated by Django 3.0.3 on 2020-07-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_auto_20200720_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='rest_kind_name',
            new_name='rest_kind_num',
        ),
    ]
