# Generated by Django 3.0.3 on 2020-07-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_auto_20200718_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_nick',
            field=models.CharField(default='이름없는 손님', max_length=100),
        ),
    ]
