# Generated by Django 3.0.3 on 2020-07-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_user_user_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(default='xxxxx@xxxx.xxx', max_length=500),
        ),
    ]
