# Generated by Django 3.0.3 on 2020-07-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_user_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='id',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rest_tele',
            field=models.CharField(default=-1, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rest_time',
            field=models.CharField(default=-1, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rest_num',
            field=models.IntegerField(default=-2, primary_key=True, serialize=False),
        ),
    ]
